- .golangci.yml
- cmd/docs/main.go
- cmd/docs/man_docs.go
- cmd/docs/md_docs.go
- hack/linter.sh
- jenkins-x.yml
> chore: enable golangci-lint

- pkg/cmd/activities/activities.go
- pkg/cmd/get/get.go
- pkg/cmd/get/get_test.go
- pkg/cmd/getlog/logs.go
- pkg/cmd/pod/pod.go
- pkg/cmd/root.go
- pkg/cmd/start/start.go
- pkg/cmd/stop/stop.go
- pkg/cmd/version/version.go
- pkg/sourcerepos/sourcerepositories.go
- pkg/sourcerepos/sourcerepositories_test.go
- pkg/tektonlog/filter.go
- pkg/tektonlog/pipelines_test.go
- pkg/tektonlog/tektonlog.go
and remove more v2 dependencies
> fix: refactored code some more

- pkg/pipelines/pipelines.go
- pkg/pipelines/pipelines_test.go
- pkg/pipelines/test_data/create/expected.yaml
- pkg/pipelines/test_data/initial/expected.yaml
- pkg/pipelines/test_data/merge/expected.yaml
- pkg/tektonlog/tektonlog.go
for multiple builds on the same context + for the build controller code
> fix: improvements in handling Pipeline Run + Activities

- pkg/cloud/buckets/buckets.go
- pkg/tektonlog/tektonlog.go
so we always pass in a context so its easier to handle timeouts and defer better
> fix: refactor the context handling of buckets code

- pkg/tektonlog/tektonlog.go
to find a PipelineActivity given a PipelineRun
> fix: add a helper method

- pkg/cmd/getlog/logs.go
- pkg/pipelines/pipelines.go
were we using the wrong labels when trying to find the PipelineActivity ;) - DOH!
> fix: find the existing PipelineActivity correctly

- go.mod
- go.sum
- pkg/cmd/lint/lint.go
- pkg/cmd/lint/lint_test.go
- pkg/cmd/lint/test_data/.lighthouse/jenkins-x/demo-deploy-kubectl.yaml
- pkg/cmd/lint/test_data/.lighthouse/jenkins-x/git-clone.yaml
- pkg/cmd/lint/test_data/.lighthouse/jenkins-x/kaniko.yaml
- pkg/cmd/lint/test_data/.lighthouse/jenkins-x/release.yaml
- pkg/cmd/lint/test_data/.lighthouse/jenkins-x/triggers.yaml
- pkg/cmd/lint/test_data/.lighthouse/jenkins-x/unit-tests.yaml
also fix the bug which broke loading of related files ;)
> fix: add unit test for lint

- pkg/tektonlog/tektonlog.go
when retrieving the running build logs, the stage name used to be hardcoded to "pipeline".
this change set the stage name to its real value.
this is needed by https://github.com/jenkins-x/jx-pipelines-visualizer/pull/72 to map the logs by stages/steps in the UI
> fix: use the right stage name in the logs

- docs/cmd/jx-pipeline.md
- docs/cmd/jx-pipeline_convert.md
- docs/cmd/jx-pipeline_effective.md
- docs/cmd/jx-pipeline_fmt.md
- docs/cmd/jx-pipeline_lint.md
- docs/man/man1/jx-pipeline-convert.1
- docs/man/man1/jx-pipeline.1
- pkg/cmd/convert/convert.go
- pkg/cmd/convert/test_data/repo/expected/.lighthouse/jenkins-x/pullrequest.yaml
- pkg/cmd/convert/test_data/repo/expected/.lighthouse/jenkins-x/release.yaml
- pkg/cmd/effective/effective.go
- pkg/cmd/fmt/fmt.go
- pkg/cmd/lint/lint.go
- pkg/cmd/override/override.go
- pkg/cmd/override/override_test.go
- pkg/cmd/override/test_data/.lighthouse/jenkins-x/release.yaml
- pkg/cmd/override/test_data/.lighthouse/jenkins-x/triggers.yaml
- pkg/cmd/root.go
- pkg/lighthouses/catalogs.go
- pkg/pipelines/processor/inliner.go
- pkg/pipelines/processor/uses_migrator.go
so its super easy to override a step locally so you can edit any of the
values
> fix: add a jx pipeline override command

- pkg/cmd/convert/convert.go
- pkg/cmd/convert/convert_test.go
> fix: default to removing Kptfile in git

- pkg/cmd/convert/convert.go
- pkg/cmd/convert/convert_test.go
- pkg/pipelines/processor/uses_migrator.go
> fix: jx pipeline convert to reuse the git sha

- go.mod
- go.sum
- pkg/cmd/convert/convert_test.go
- pkg/cmd/override/override.go
- pkg/cmd/override/override_test.go
- pkg/cmd/override/test_data/.lighthouse/jenkins-x/pullrequest.yaml
- pkg/cmd/override/test_data/.lighthouse/jenkins-x/triggers.yaml
- pkg/cmd/override/test_data/expected.yaml
- pkg/lighthouses/catalogs.go
- pkg/pipelines/processor/inliner.go
so it finds catalog files via the correct git URI
also added an integration test to ensure it keeps working
> fix: fixed pipeline override

- .goreleaser.yml
- Makefile
- cmd/effective/main.go
- go.mod
- go.sum
for just running jx-pipeline-effective
> fix: add separate binary

- pkg/cmd/effective/effective.go
so we can see what the default parameter values will be
> fix: add option to default parameters for repo url

- pkg/cmd/effective/effective.go
not the PipelineSpec so that they work better
> fix: specify the parameter defaults on the PipelineRun spec

- pkg/cmd/effective/effective.go
Avoids the need to resolve every pipeline in the triggers file - which can sometimes take a bit of time if using `uses:` syntax
> feat: defer resolving the pipeline until after the name is selected

- pkg/tektonlog/tektonlog.go
> fix: tektonlog: be smarter when waiting for pod completion

- pkg/tektonlog/tektonlog.go
follow up on #385
see https://github.com/jenkins-x-plugins/jx-pipeline/pull/385#discussion_r635983803
let's try to keep the backward compatibility with old tekton (jx2...) for people using the jx-pipelines-visualizer on an old v2 cluster
also avoid a potential nil pointer dereference
> fix: tektonlog backward compatibility with jx2

- pkg/cmd/fmt/fmt.go
> fix: avoid panic when taskspec is nil

- .golangci.yml
- pkg/pipelines/pipelines.go
- pkg/pipelines/pipelines_test.go
> fix: increment build numbers

- pkg/cmd/start/start.go
> fix: remove tovalid call from lh spec ref

- go.mod
- go.sum
Need to re-trigger the release pipeline.
> chore: upgrade lh-client

- pkg/pipelines/pipelines.go
> fix: do not set activity status if pipeline status is unknown

- pkg/pipelines/pipelines.go
- pkg/pipelines/pipelines_test.go
- pkg/pipelines/testdata/cancel-with-steps/pr.yaml
We show cancelled for pipelines that are cancelled before a step has started, this PR adds support to show cancelled for pipelines which have a completed step, and then the pipeline was cancelled.
> fix: set status as cancelled for cancelled tkn prs with steps

- Makefile
I've update the go version in makefile
cc @ankitm123
> fix: update go version in makefile

- .github/workflows/codeql-analysis.yml
> fix: add security extended and quality queries to codeql

- go.mod
- go.sum
> fix: update json iterator package to fix panics

- go.mod
- go.sum
> chore: upgrade helper to 3.2.11

- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
- Makefile
- README.md
> test: enable codecov

- .goreleaser.yml
As part of supply chain security project, we are going to generate sbom for every jx binary
> feat: generate sbom for jx-pipeline binaries

- .goreleaser.yml
- .lighthouse/jenkins-x/release.yaml
> feat: add sbom generation to jx-pipeline

- .lighthouse/jenkins-x/release.yaml
> fix: missing executable in goreleaser

- .gitignore
- .goreleaser.yml
> fix: add syft and codecov to gitignore

- .lighthouse/jenkins-x/release.yaml
Signed-off-by: osamamagdy <osamamagdy174@gmail.com>
This needs https://github.com/jenkins-x/jx3-pipeline-catalog/pull/1166 to be merged first
> feat: reference download syft from pipeline catalog

- .lighthouse/jenkins-x/release.yaml
Signed-off-by: osamamagdy <osamamagdy174@gmail.com>
It references the task created in my fork of the jx3-pipeline-catalog.
If it's working we can open a pr in the jx3-pipeline-catalog and update this pr accordingly
> feat: container sbom push

- .lighthouse/jenkins-x/release.yaml
Signed-off-by: osamamagdy <osamamagdy174@gmail.com>
> fix: revert the sbom container push

- .lighthouse/jenkins-x/release.yaml
Signed-off-by: osamamagdy <osamamagdy174@gmail.com>
> feat: add supply chain tasks

- .gitignore
- .lighthouse/jenkins-x/release.yaml
> fix: create image tar for sbom analysis

- .gitignore
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
- Makefile
> fix: add cred helpers and sbom to gitignore

- pkg/cmd/getlog/logs.go
- pkg/cmd/getlog/tekton_logs.go
- pkg/cmd/getlog/tekton_logs_win.go
- pkg/cmd/lint/lint.go
- pkg/lighthouses/pipelines.go
- pkg/pipelines/processor/helpers.go
The introduction of setOutput made the input to the pager close before the logs where output to it.
This fixes that
Also doing some wording fixes while at it
> fix: Using pager for logs

- pkg/pipelines/pipelines.go
> fix: only update stage message when steps exist in pipeline activity

- pkg/cmd/start/start.go
- pkg/cmd/start/start_test.go
Fixes https://github.com/jenkins-x/jx/issues/8419
Signed-off-by: Rahul Tiwari <jprrahultiwari@gmail.com>
> fix: custom envs to spec template
